# Generated by Django 4.2.7 on 2026-01-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('saga', models.CharField(blank=True, max_length=200)),
                ('start_episode_number', models.IntegerField(default=1)),
                ('end_episode_number', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['start_episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('epithet', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('PIRATE', 'Pirate'), ('MARINE', 'Marine'), ('REVOLUTIONARY', 'Révolutionnaire'), ('CIVILIAN', 'Civil'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('bounty', models.IntegerField(default=0)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ALIVE', 'Vivant'), ('DEAD', 'Mort'), ('UNKNOWN', 'Inconnu')], default='ALIVE', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevilFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('romanji', models.CharField(blank=True, max_length=200)),
                ('fruit_type', models.CharField(choices=[('PARAMECIA', 'Paramecia'), ('ZOAN', 'Zoan'), ('LOGIA', 'Logia')], default='PARAMECIA', max_length=20)),
                ('ability', models.TextField()),
                ('weaknesses', models.TextField(blank=True)),
                ('rarity', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('LOST', 'Perdu'), ('UNKNOWN', 'Inconnu')], default='ACTIVE', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('first_appearance_arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fruits', to='knowledge.arc')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FruitHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_history', to='knowledge.character')),
                ('devil_fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='knowledge.devilfruit')),
            ],
            options={
                'ordering': ['-is_current', '-from_date'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='knowledge.arc')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ship_name', models.CharField(blank=True, max_length=200)),
                ('base_location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='knowledge.character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='members', to='knowledge.crew'),
        ),
        migrations.AddField(
            model_name='character',
            name='first_appearance_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_first_appearance', to='knowledge.episode'),
        ),
    ]
